waycrate/wayshot

Cargo.toml
README.md
src/main.rs

I don't have access to multiple monitors right now, if someone could test this then that would be great. 
I'm 99% sure this will work.

Add per output screenshot.

---

src/backend.rs
src/convert.rs
src/wayshot.rs

I experiment with render_bit_depth option in sway and found that nothing can make screenshots in this mode. So I've added this feature. I only support Xbgr2101010 and Abgr2101010 because I don't have anything to test it on Xrgb2101010 or Argb101010 formats.
- Allow user to make screenshots if back buffer uses 10 bits per color channel.
- Image conversion moved to convert.rs

Added 10-bit back buffer support

---

docs/wayshot.1.scd
src/wayshot.rs

This makes it possible to capture a region using `wayshot -s "$(slurp)"`, which requires less work to type than `wayshot -s "$(slurp  -f '%x %y %w %h')" `. Both the current ("%X %Y %W %H") and slurp default ("%X,%Y %Wx%H")  geometry formats can be used.

[feature] Parse slurp's default geometry output format

---

wayshot/src/output.rs

This commit adds a field to `struct OutputInfo` corresponding to the output transform, and adjusts the code called by `get_all_outputs` to fill in this field using the [wl_output::geometry](https://docs.rs/wayland-client/latest/wayland_client/protocol/wl_output/enum.Event.html#variant.Geometry) event.
This is a small step toward supporting output transforms, and may be useful for https://github.com/waycrate/wayshot/pull/41 .

[feat] Record output geometry transforms

---

libwayshot/src/lib.rs

this maybe can make screen overlay a bit faster

chore: when make a big image,loop skip first one

---

libwayshot/src/lib.rs

chore: wl-output can use reference

---

libwayshot/src/error.rs
libwayshot/src/lib.rs

https://github.com/pop-os/xdg-desktop-portal-cosmic/blob/master_jammy/src/wayland.rs#L191
from the code in xdg-desktop-portal-cosmis, here should pass a rawfd to it , so maybe expose a function is better?

chore: allow pass row fd to capture

---

libwayshot/src/image_util.rs
libwayshot/src/lib.rs
libwayshot/src/screencopy.rs
wayshot/src/wayshot.rs

I was working on the freezing functionality and along the way I'll use this PR to include some performance improvements.
`image_util::rotate_image_buffer` did 1-2 unneeded resizes. Remove the first one if the transform is a normal (or default) and remove the second if the requested size is the same as the original size.
<details>
<summary>Flamegraph before</summary>
</details>
<details>
<summary>Flamegraph after</summary>
</details>
I noticed a run in release mode going from ~0.24s to ~0.13s. I could use `hyperfine` for a better comparison, but I think the flamegraph speaks for itself.

Performance Tuning

---

libwayshot/src/lib.rs

since wayland-rs use borrowedfd, so here do not need unsafe anymore

chore: remove unsafe from rawfd

---

Cargo.lock
libwayshot/Cargo.toml
libwayshot/src/dispatch.rs
libwayshot/src/lib.rs
libwayshot/src/screencopy.rs
wayshot/Cargo.toml
wayshot/src/clap.rs
wayshot/src/utils.rs
wayshot/src/wayshot.rs

Apologies for the multiple features in a single diff, let me know if you want me to split the diff. This is what has changed:
1. Use [`tracing`](https://docs.rs/tracing/latest/tracing/index.html) instead of `log` as it's more powerful. It allows you to add [instrumentation](https://docs.rs/tracing/latest/tracing/attr.instrument.html) and has a bunch of crates to make telemetry better. 
2. Use `stderr` for logging. At the same time changed it so when using `--stdout`, it does not conflict with `--debug`.
3. In various locations use threads to do operations in paralllel leading to the below ~33% performance improvement for 3 screens. This primarily affects image stuff.
For this last item I tried to use rayon first but there wasn't much difference with a scoped thread implementation besides …

Add tracing, stderr logging, and parallel image alterations

---

Cargo.lock
Cargo.toml
libwayshot/Cargo.toml
wayshot/Cargo.toml

this can be used to control same dependencies, version ,edition and license

feat: use workspace package control global values

---

libwayshot/src/convert.rs
libwayshot/src/image_util.rs
libwayshot/src/lib.rs
libwayshot/src/screencopy.rs

Hello,
I use the dev version of Sway with NVidia proprietary drivers and I'm unable to take a screenshot using Wayshot.
```
2024-01-08T16:56:40.302884Z ERROR libwayshot: No suitable frame format found
Error: NoSupportedBufferFormat
```
Turns out that with my setup, the frame format is BGR888, which is not supported yet. So here is a small PR that seems to make it work for me.
BGR888 is a 3-byte-per-pixel frame format with no transparency, unlike other formats used so far. So in `convert_inplace`, there is no room in the buffer to turn it into an RGBA image. As a workaround, I use a `DynamicImage` type in subsequent operations to handle both RGB and RGBA formats.
I'm aware this may not be the best solution, please let me know if there is anything I can do to improve this code :)

feat: add support for BGR888 image format

---

libwayshot/src/dispatch.rs
libwayshot/src/image_util.rs
libwayshot/src/lib.rs
libwayshot/src/output.rs
libwayshot/src/region.rs
libwayshot/src/screencopy.rs

In #78 it was discussed that master did not support scaled displays. The way screenshotting works is that screencopies are requested in logical regions (so after scaling, a pixel is not a real world pixel), but they're actually saved as "physical" regions (before scaling, aka the unit is 1 real world pixel). Some issues that I fixed were:
1. We created the final image as a "logical" size. So when someone took a screenshot of a 4K screen that was scaled 200%, the picture in memory would be 4K but we would create a 1080p size output file. A 4K output file would now be created.
2. Following the previous step, we need to convert the "logical" region to a "phyiscal" region, aka scale it as well.
But how and where do we scale? From all of the outputs, we take the maximum scale and make sure to …

Fix: support correct saving for scaled displays

---

libwayshot/src/lib.rs

There is no need to do roundtrip two times.

chore: remove useless roundtrip

---

Cargo.lock
wayshot/Cargo.toml
wayshot/src/cli.rs
wayshot/src/wayshot.rs

This PR adds a --clipboard flag and implements functionality to make the screenshot available on the clipboard using wl-clipboard-rs. All the caveats described in https://github.com/waycrate/wayshot/pull/89#issue-2151702439 are still applicable:
> - Reading up on the protocol, it appears that a process can only offer data to be copied only for as long as it stays alive. This is mostly fine for GUI apps but problems arise when you want to copy something to the clipboard and exit as a terminal app. Basically with this PR wayshot will offer up the screenshot for a small moment and immediately exit.
> - What this means in practice is that the clipboard functionality in this PR is unusable without a clipboard manager setup. If you have a clipboard manager listening, it will copy the screenshot …

feat(clipboard): implement clipboard integration

---

Cargo.lock
docs/wayshot.1.scd
wayshot/Cargo.toml
wayshot/src/utils.rs

As title says, adds support for `.webp` screenshots output extension. Shouldn't add any complexity/burden to support, I think.

Add support for webp

---

libwayshot/src/lib.rs
libwayshot/src/region.rs
wayshot/src/wayshot.rs

refactor: remove unnecessary to_string()

---

Cargo.lock
wayshot/src/cli.rs
wayshot/src/wayshot.rs

Currently Wayshot save screenshots in the current working directory. However this is not ideal as some users like to save screenshots in a particular directory(For example $HOME/Pictures/screenshots).
This PR introduces a `--folder` flag which allows users to select save directory for their screenshots.

accounting for directories in file path

---

libwayshot/src/lib.rs

Modifies the overlay creation function to destroy the shell surfaces after use. Not much familiar with layer shell so input from @AndreasBackx would be appreciated on if this is all that is required. I have moved the slurp callback activation into that function too because it needs to be called before the surface is destroyed and destroying the surface needs context only present within this function.

feat(clipboard): fix interaction with freeze and select feature: Issue #109

---

libwayshot/src/lib.rs

Attempts to solve the freeze feature crashing sporadically  as described in https://github.com/waycrate/wayshot/issues/109#issuecomment-2051750240
https://github.com/waycrate/wayshot/issues/109#issuecomment-2052105490 :
> Alright, I have a patch that solves this. The existing code destroys the layer_shell object instead of the layer_surface objects, destroying only layer_surface objects seems to solve the issue but destroying both in that order doesn't. It isn't clear to me why this is the case but I'll create a PR for you to test.
@Gigas002 can you test this fix?

Destroy layer shell surfaces instead of layer shell for freeze-feat

---

wayshot/src/utils.rs

Missed in the PR #98 I proposed with this feature, sorry.
Was implemented as part of #104, but since there was a request to separate stuff from it here's this PR

Add missing conversion from_str to webp enum

---

Cargo.lock
libwayshot/Cargo.toml
libwayshot/src/screencopy.rs
wayshot/Cargo.toml
wayshot/src/wayshot.rs

As title says, this PR proposes replacement of `nix` crate with [rustix](https://github.com/bytecodealliance/rustix).
Currently, the only package dependent on `nix` is a `wl-clipboard-rs`, and it's moving from `nix` to `rustix` as well in upcoming update to match the `wayland-rs`: https://github.com/YaLTeR/wl-clipboard-rs/commit/e81562a06b4c4879bd14524c86c866654a17e4b2
This change simplifies dependency tree for a bit and the migration is pretty straightforward. If there's any downsides I'm not aware of these.

Replace nix with rustix

---

Cargo.lock
libwayshot/Cargo.toml
libwayshot/src/screencopy.rs
wayshot/Cargo.toml
wayshot/src/wayshot.rs

I think, [rustix](https://github.com/bytecodealliance/rustix/releases/tag/v1.0.0) stabilizes it's API with this major update, thankfully only minor changes required for `wayshot`

dependencies: bump rustix to 1.0

---

.github/dependabot.yml

Now that ci build is fixed, I think is a good time to introduce automated dependabot versions scans

ci: add dependabot scans

---

Cargo.lock
wayshot/Cargo.toml
wayshot/src/utils.rs

[Avif](https://aomedia.org/blog%20posts/avif-meet-the-next-level-image-file-format/) is an open-source, royalty-free high-compression ratio lossless/lossy image format by **Allicance for Open Media**. It's pretty similar to `JPEG-XL`, but since it's support is still lacking in `image-rs` and doesn't seem to appear soon, while we have demand (#11) for similar format and it's very easy to introduce without breaking stuff.
As a downside, if your PC's hardware doesn't support hardware decoding (I suppose something around RDNA3+/RTX40 series GPUs introduced both hardare encoding and decoding for `avif`) it will be hella slow and not recommended. In other case, I personally think it's the best format for both lossy and lossless images storage.

feat: add avif extension support

---

libwayshot/src/lib.rs

- use `ok_or_else()` function to check if frame format exists in `capture_output_frame_get_state_shm()` function
- fixed "failed to create compositor" tracing error message
- fixed typo in `screenshot_single_output()` function's comment

chore: minor improvements in libwayshot lib.rs

---

libwayshot/examples/waymirror-egl/src/dispatch.rs
libwayshot/examples/waymirror-egl/src/main.rs
libwayshot/examples/waymirror-egl/src/state.rs
libwayshot/examples/waymirror.rs

- Rename the `egl` variable to `egl_instance` to avoid confusion in waymirror-egl state
- Fix a typo in `waymirror.rs`
- Add a keybind `<ESC>` to terminate a waymirror-egl instance

chore: improvements in waymirror-egl example

---

libwayshot/src/lib.rs

I want to expose it for xdg-desktop-portal to find the right format of the video

chore: expose capture_output_frame_get_state_shm

---

.github/workflows/build.yml
Cargo.lock
README.md
docs/wayshot.1.scd
docs/wayshot.7.scd
libwayshot/src/error.rs
libwayshot/src/lib.rs
libwayshot/src/region.rs
wayshot/Cargo.toml
wayshot/src/cli.rs
wayshot/src/utils.rs
wayshot/src/wayshot.rs

resolve: https://github.com/waycrate/wayshot/issues/1

feat: use libwaysip instead of slurp

---

.editorconfig
flake.lock
flake.nix
shell.nix

FYI: you can test these with
```nix
rm -rf target
cargo vendor
nix develop -i --command cargo b
./target/debug/wayshot
./target/debug/waymirror-egl
```
Should I make a Nix package for wayshot? I'm guessing no since it's already in Nixpkgs and there's really no good reason to use a newer version

chore: update Nix flake

---

libwayshot/src/lib.rs

This PR adds two utility functions, designed to be used by [`xdg-desktop-portal-luminous`](https://github.com/waycrate/xdg-desktop-portal-luminous):
- `get_available_frame_formats`:  returns a vector of valid formats for a given `WlOutput`. The original idea was to pick a random `WlOutput` from the connection, performing a 1-pixel screenshot to obtain the valid formats using `wlr-screencopy` protocol, and saving them in a `LazyCell`. I preferred to capture the entire screen from a given `WlOutput` passed as parameter instead, to return a vector of `FrameFormat` which contain additional information such as the size and the stride of the buffer. This makes the function more general purpose, allowing it to be used in multiple contexts. For example, right now only 4-bytes pixel formats are …

Add utility functions to support screencasting in xdg-desktop-portal-luminous
